[window]
padding = { x = 3, y = 0 }
opacity = 0.9


[font]
normal.family = "DroidSansM Nerd Font"
bold.family = "DroidSansM Nerd Font"
italic.family = "DroidSansM Nerd Font"
bold_italic.family = "DroidSansM Nerd Font"
size = 10


[mouse]
hide_when_typing = true


[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
	{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
	{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
]


[colors]
primary = { "background" = "0x191919", "foreground" = "0xeaeaea" }
cursor = { "cursor" = "0xff2600", "text" = "0xf1c1c1" }


[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"
