import = [
    "~/.config/alacritty/theme.toml"
]

[window]
padding = { x = 3, y = 0 }
opacity = 0.9
decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "Hack Nerd Font"
size = 10


[mouse]
hide_when_typing = true


[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
	{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
	{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"
