[window]
padding = { x = 3, y = 3 }
opacity = 0.8
decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "JetBrains Mono Nerd Font"
size = 10

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
	{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
	{ key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[terminal.shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

